config/routes.rb
Rails.application.routes.draw do
  resources :reviews
resources :students
  root 'courses#index'#devise require a root route
  resources :courses do 
    resources :students, only:[:index]
    resources :reviews, only: [:index,:new]
  end
  devise_for :users ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :students, through: :reviews

  validates :course_name, :profesor_name,:course_length,:number_videos, presence: true, uniqueness: {scope: :user_id}
  
  scope :beta,->{order('LOWER(course_name)')} 
  def self.search (course_name)
      Course.where("course_name LIKE ?", "%#{course_name}%").beta
  
  end 
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :course
  belongs_to :student
  validates :ratings, :comments ,presence: true

   #validate :filter

  def filter
  
    ar = ["fuck","worse"]
    ar.each do |t|
      errors.add(:comments, "Not")
    end
  end
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :reviews
    has_many :courses, through: :reviews
    validates :student_name,:studentID,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :students, through: :courses
  has_many :reviews, through: :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable ,:omniauthable, omniauth_providers: %i[github] # optional


         def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0, 20]
            user.phone_number = auth.info.phone_number   # assuming the user model has a name
            # user.image = auth.info.image # assuming the user model has an image
            # If you are using confirmable and the provider(s) you use validate emails, 
            # uncomment the line below to skip the confirmation emails.
            # user.skip_confirmation!
          end
        end


        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    def record_not_found
        #render plain:"404 Not Found"#, status: 404
         #redirect_to root_path
       flash[:message] = "404 Not Found"
       redirect_to root_path
       



    end
    protected


def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:phone_number])
end 
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_course, only:[:show,:edit, :update, :destroy]
    def index
        
            @courses = current_user.courses.search(params[:search])
    end
   def show 
   end
 def new
    @course = Course.new
 end
 def create

    @course =current_user.courses.build(course_params)
    if @course.save
        redirect_to course_path(@course) 
    else

        render :new
    end 
 end
 def edit
end

def update
    if @course.update(course_params)
        redirect_to course_path(@course)
    else
     render :edit
    end
end

def destroy
    @course.destroy
    redirect_to courses_path
end
   private

def set_course
    @course = current_user.courses.find(params[:id]) 
end
def course_params#strong_params
    params.require(:course).permit(:course_name,:profesor_name, :course_length, :number_videos,:search)
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!

    before_action :set_review, only:[:show,:edit, :update, :destroy]

    def index
       @course = current_user.courses.find_by_id(params[:course_id])
       if @course
        @reviews = @course.reviews
       else
          @reviews = current_user.reviews
  
    end
end
    def show
    end

    def new
        @course = current_user.courses.find_by_id(params[:course_id])
        @student = Student.find_by_id(params[:id])
        if @course
            @review = @course.reviews.build
        elsif @student
            @review = @student.reviews.build
        else
        @review = Review.new
        end
end

def create
    @review = Review.new(review_params)
    if @review.save
        redirect_to review_path(@review)

    else
      render :new  
    end
end

    def edit

    end

    def update
        if @review.update(review_params)
           redirect_to review_path(@review)
       else
        render :edit
       end
    end

    def destroy
        @review.destroy
        redirect_to reviews_path
    end
private

def set_review
    @review = current_user.reviews.find(params[:id])   
end
def review_params
    params.require(:review).permit(:ratings,:comments,:course_id, :student_id)
end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

before_action :authenticate_user!
before_action :set_student, only:[:show,:edit, :update, :destroy]


def index
    @course = current_user.courses.find_by_id(params[:course_id])
   if @course
    @students = @course.students.all
   else

    @students = Student.all
   end
end
def show
end

def new
   @student = Student.new
end
def create

@student =Student.new(student_params)
if @student.save
    redirect_to student_path(@student) 
else

    render :new
end 

def create
    @student = Student.new(student_params)
    if @student.save
        redirect_to student_path(@student)
    else
        render :new
    end
end
end

private


def set_student
   @student = Student.find(params[:id])

end
def student_params
  params.require(:student).permit(:student_name, :studentID)
end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
      else
        session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url
      end
    end
    def failure 
      redirect_to root_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper

def display_errors(record)
render partial: 'errors_partial/errors', locals: {object: record}
end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= display_errors(course)%> <%# helper method%>

<div style="border: 2px solid red; border-radius: 5px; text-align:center; background-color:orange;>
<%=form_for course do |f| %> <%#= is better to use local variable%>

    <%=f.label :course_name,"Course Name:"%>
    <%=f.text_field :course_name%>
    <br><br>
    
    <%=f.label :profesor_name,"Profesor Name:"%>
    <%=f.text_field :profesor_name%>
    <br><br>
    <%=f.label :course_length,"Course length:"%>
    <%=f.text_field :course_length%>
    <br><br>
    <%=f.label :number_videos,"Nomber of Videos:"%>
    <%=f.number_field :number_videos%>
    <br><br>
    <%=f.submit "Create a course"%>
    <%end%>
    </div>

app/views/courses/edit.html.erb
<h6>
Edit Course 
</h6>

<%#= display_errors_for(@student)%>
<%= form_for(@course) do |f|%>
   <div> <%=f.label :course_name, "Course Name"%>
    <%=f.text_field :course_name%></div>
    <br><br>
   <div> <%=f.label :profesor_name, "Profesor Name:"%>
    <%=f.text_field :profesor_name%></div>
    <br><br>
    <div> <%=f.label :course_length, "Course Length:"%>
    <%=f.text_field :course_length%></div>
    <br><br>
    <div> <%=f.label :number_videos, "Number of Videos:"%>
    <%=f.text_field :number_videos%></div>
    <br><br>
  <div style="border: 2px solid red; 
  border-radius: 25px; text-align:center; background-color:orange;">
  <%=f.submit "Update course"%></div>
<%end%>

app/views/courses/index.html.erb
<div style="border: 2px solid red; 
border-radius: 25px; text-align:center; background-color:orange;">


All courses
</div> <br>

<% @courses.each do |course| %>
    <div style="border: 2px solid red;display:no; 
    border-radius: 25px; text-align:center; background-color:orange; color:blue;">
    <p> Course Name:<%= link_to course.course_name, course_path(course)%> </p>
    
    <%end%>

    <h6 style="border: 2px solid black; 
    border-radius: 2px; text-align:center; background-color:black;">
    
    <%=link_to 'Add a Course',new_course_path%> 
    
    </h6><br>
    
    

app/views/courses/new.html.erb
<h6> New Course</h6>

 <%=render partial: 'form', locals: {course: @course}%>

app/views/courses/show.html.erb
<h6>Course Name: <%=@course.course_name%></6>
<h6>Profesor Name: <%=@course.profesor_name%></h6>
<h6>Course Length: <%=@course.course_length%></h6>
<h6>Number of Videos :<%=@course.number_videos%></h6>
<h6 style="border: 2px solid red; border-radius: 5px; text-align:center; background-color:orange;">
<%=link_to 'Edit a Course', edit_course_path(@course)%>
</h6>
<h6 style="border: 2px solid red; border-radius: 5px; text-align:center; background-color:orange;"
<h6><%=form_tag(review_path(@course), method: :delete) do %>

    <%=submit_tag "Delete a course"%>
    
<%end%>
</h6>

<h6> <%=link_to "#{@course.profesor_name}'s reviews",course_reviews_path(@course)%>
<h6> <%=link_to "Set up a review for #{@course.profesor_name}",new_course_review_path(@course)%>
<h6> <%=link_to " #{@course.profesor_name}s' students'",course_students_path(@course)%>

app/views/errors_partial/_errors.html.erb
<div style="border: 2px solid red; border-radius: 5px; text-align:center; background-color:orange;>

<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%=object.class %> from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElearningAppRubyRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <nav   style ="background-color:#0B103D; color: white;border: 2px solid red; 
  border-radius:5px; text-align:center;">
  
    
  <%=link_to 'Courses', courses_path%>
  <%=link_to 'Students', students_path%>
  <%=link_to 'Reviews', reviews_path%>
    <%if user_signed_in?%>
    <%=form_tag(courses_path, :method =>'get') do %>
      <%=search_field_tag :search, params[:search], placeholder: "Search"%>
      <%= submit_tag ("Search Only courses in db")%>
      <%end%>

    <%=form_tag(destroy_user_session_path, method: :delete, style: "display:inline-block;") do %>
      <%=submit_tag "Sign Out"%>
      <%end%>
      <%else%>
      <%=link_to "Sign in with Github", user_github_omniauth_authorize_path%>
      <%=link_to 'Sign Up', new_user_registration_path%>
      <%=link_to 'Sign In',new_user_session_path%>
      <%end%>
    </nav>
  
  <p class="notice"><%= notice -%></p>
  <p class="alert"><%= alert %></p>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= display_errors(review)%> <%# helper method%>

<div style="border: 2px solid red; border-radius: 5px; text-align:center; background-color:orange;>
<%=form_for review do |f| %> <%#= is better to use local variable%>
<%=f.collection_select :course_id,current_user.courses,:id,:profesor_name%><br><br>
<%=f.collection_select :student_id,Student.all,:id,:studentID%><br><br>

<%=f.label :ratings, "Ratings"%>
<%=f.text_field :ratings%>
<br><br>

<%=f.label :comments, "Comments"%>
    <%=f.text_field :comments%>
    <br><br>
    
    
    <%=f.submit "Create a review"%>
    <%end%>
    </div>

app/views/reviews/edit.html.erb
<h6>Edit Review</h6>

<%=render partial: 'form', locals: {review: @review}%>

<%=link_to "Edit a review", edit_review_path(@review)%>

app/views/reviews/index.html.erb
# <h6 style ="background-color:#0B103D; color: white;border: 2px solid red; 
# border-radius: 25px; text-align:center;"> 

# Reviews
# </h6>

<h6>Reviews</h6>
<button> <%=link_to "Add a review", new_review_path%></button>

<%@reviews.each do |reviewed|%>
    <div style ="background-color:#0B103D; color: white;border: 2px solid red; 
    border-radius: 25px; text-align:center; display-style:none;">


    <span>Rating :<%=reviewed.ratings%></span><br>
    <span>Comments: <%= reviewed.comments%></span>
    <h6>Reviewed</h6>
    <p><%=link_to 'review', review_path(reviewed)%>
     <span> For<%=link_to reviewed.course.profesor_name, course_path(reviewed.course)%></span><br>
     <span> By<%=link_to reviewed.student.studentID, student_path(reviewed.student)%></span>
     </p>
    <%end%>
    </div>

app/views/reviews/new.html.erb
<h6>New Review</h6>

<%=render partial: 'form', locals: {review: @review}%>

app/views/reviews/show.html.erb
<h6> Review Details</h6>
 <h6>Profesor Name: <%=link_to @review.course.profesor_name,course_path(@review.course)%></h6>
<h6>Student Identification: <%=link_to @review.student.studentID,student_path(@review.student)%></h6>
<h6>Ratings:  <%=@review.ratings%></h6>
<h6>Comments:  <%=@review.comments%></h6>

<h6><%=form_tag(review_path(@review), method: :delete) do %>

    <%=submit_tag "Delete a review"%>
    
    <%end%></h6>

app/views/students/_form.html.erb
<%= display_errors(student)%> <%# helper method%>

<div style="border: 2px solid red; border-radius: 5px; text-align:center; background-color:orange;>
<%=form_for student do |f| %> <%#= is better to use local variable%>

    <%=f.label :student_name, "Student Name"%>
    <%=f.text_field :student_name%>
    <br><br>
    
    <%=f.label :studentID, "Student ID:"%>
    <%=f.number_field :studentID%>
    <br><br>
    <%=f.submit "Create a student"%>
    <%end%>
    </div>

app/views/students/index.html.erb
<h6>Students</h6>

<div style="border: 2px solid red; 
border-radius: 25px; text-align:center; background-color:orange;">

<%=link_to 'Add a student',new_student_path%> 

</div><br>

<% @students.each do |student| %>
    <div style="border: 2px solid red; 
    border-radius: 25px; text-align:center; background-color:orange; color:blue;">
    <p> Student Name:<%= link_to student.student_name, student_path(student)%> </p>
    <p> Student Identification:<%=student.studentID%> </p><br><br><div>
    
    <%end%>

app/views/students/new.html.erb
<h6> New Student</h6>

<%=render partial: 'form', locals: {student: @student}%>

app/views/students/show.html.erb
<h6><%=@student.student_name%></h6>